// Generates src/generated/*.ts from public/: the logo paths (so the logo can
// be animated per letter) and a manifest of which optional assets exist, so
// scenes fall back to coded artwork when a file is missing.
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const pub = path.join(root, "public");
const outDir = path.join(root, "src", "generated");
fs.mkdirSync(outDir, { recursive: true });

const logoFile = path.join(pub, "brand", "logo.svg");
let logo = { exists: false, green: "", white: "", width: 2366, height: 631 };
if (fs.existsSync(logoFile)) {
  const svg = fs.readFileSync(logoFile, "utf8");
  const pathD = (id) => svg.match(new RegExp(`id="${id}"[^>]*\\sd="([^"]+)"`))?.[1] ?? "";
  const vb = svg.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/);
  logo = {
    exists: true,
    green: pathD("green"),
    white: pathD("white"),
    width: vb ? Number(vb[1]) : 2366,
    height: vb ? Number(vb[2]) : 631,
  };
}
fs.writeFileSync(
  path.join(outDir, "logoPaths.ts"),
  `// Generated by scripts/prepare.mjs from public/brand/logo.svg. Do not edit.\n` +
    `export const LOGO = ${JSON.stringify(logo)} as const;\n`,
);

const optional = [
  "cards/hero.png",
  "cards/trade.png",
  ...Array.from({ length: 8 }, (_, i) => `cards/extra-0${i + 1}.png`),
  "avatars/you.png",
  "avatars/maya.png",
  ...Array.from({ length: 5 }, (_, i) => `avatars/c${i + 1}.png`),
];
const present = optional.filter((f) => fs.existsSync(path.join(pub, f)));
fs.writeFileSync(
  path.join(outDir, "assets.ts"),
  `// Generated by scripts/prepare.mjs. Do not edit.\n` +
    `export const PRESENT_ASSETS: readonly string[] = ${JSON.stringify(present, null, 2)};\n`,
);
console.log(`prepare: logo ${logo.exists ? "found" : "MISSING"}; assets present: ${present.length}/${optional.length}`);
const missing = optional.filter((f) => !present.includes(f));
if (missing.length) console.log(`prepare: using coded fallbacks for ${missing.join(", ")}`);
